config/routes.rb
Rkkinfo::Application.routes.draw do
  resources :customers

  resources :sixmonth_customers

  get "login2/login_page"
post "login2/login_page"
post "login2/logout"

  get "login1/login_page"
post "login1/login_page"
post "login1/logout"

  get "login/login_page"
  post "login/login_page"
post "login/logout"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :employees

  resources :twoyear_customers

  resources :oneyear_customers

  resources :instant_customers

end

app/models/sixmonth_customer.rb
class SixmonthCustomer < ActiveRecord::Base
  attr_accessible :e_mail, :emp_no, :feedback, :issue, :name, :phone, :status, :trouble_shooting_steps, :plan

	 scope :new_customer,where( 'created_at between ? and ?', Date.today, Date.tomorrow)
    validates :e_mail, :format => { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/,
    :message => "Wrong Format" }
     validates_presence_of :emp_no, :e_mail, :name, :phone
     def self.search(search)
  if search
    order('created_at desc').find(:all, :conditions => ['cast(emp_no as text) LIKE ?', "%#{search}%"])
  else
    order('created_at desc').find(:all)
  end
end
end

app/controllers/sixmonth_customers_controller.rb
class SixmonthCustomersController < InheritedResources::Base
def index
        @sixmonth_customers = SixmonthCustomer.search(params[:emp_no])
if !session[:logged_in]
  redirect_to :controller => 'login1',
              :action => 'login_page'
  return
end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sixmonth_customers }
    end
  end

  # GET /oneyear_customers/1
  # GET /oneyear_customers/1.json
  def show
    @sixmonth_customer = SixmonthCustomer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sixmonth_customer }
    end
  end

  # GET /oneyear_customers/new
  # GET /oneyear_customers/new.json
  def new
    @sixmonth_customer = SixmonthCustomer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sixmonth_customer }
    end
  end

  # GET /oneyear_customers/1/edit
  def edit
    @sixmonth_customer = SixmonthCustomer.find(params[:id])
  end

  # POST /oneyear_customers
  # POST /oneyear_customers.json
  def create
    @sixmonth_customer = SixmonthCustomer.new(params[:sixmonth_customer])

    respond_to do |format|
      if @sixmonth_customer.save
        format.html { redirect_to @sixmonth_customer, notice: 'Six months customer was successfully created.' }
        format.json { render json: @sixmonth_customer, status: :created, location: @sixmonth_customer }
      else
        format.html { render action: "new" }
        format.json { render json: @sixmonth_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /oneyear_customers/1
  # PUT /oneyear_customers/1.json
  def update
    @sixmonth_customer = SixmonthCustomer.find(params[:id])

    respond_to do |format|
      if @sixmonth_customer.update_attributes(params[:sixmonth_customer])
        format.html { redirect_to action: :index }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sixmonth_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oneyear_customers/1
  # DELETE /oneyear_customers/1.json
  def destroy
    @sixmonth_customer = SixmonthCustomer.find(params[:id])
    @sixmonth_customer.destroy

    respond_to do |format|
      format.html { redirect_to sixmonth_customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sixmonth_customers_helper.rb
module SixmonthCustomersHelper
end

app/views/sixmonth_customers/_form.html.erb
<%= form_for @sixmonth_customer, :validate => true, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group" style="color:#1C9DD6">
    <%= f.label :emp_no, :class => 'control-label' %>
    <div class="controls">
<%= f.select :emp_no, Employee.all.collect(&:no) %>    
    </div>
  </div>
  <div class="control-group" style="color:#1C9DD6">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group" style="color:#1C9DD6">
    <%= f.label :e_mail, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :e_mail, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group" style="color:#1C9DD6">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
   <div class="control-group" style="color:#1C9DD6">
    <%= f.label :plan, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :plan, :class => 'text_field', :value => "$129" %>
    </div>
  </div>
  <div class="form-actions">
<form class="form-search">
    <button type="submit" class="btn">Proceed</button>
    </form>   
  </div>
<% end %>

app/views/sixmonth_customers/edit.html.erb
<html>
<br>
<%- model_class = SixmonthCustomer -%>

<%= form_for @sixmonth_customer, :html => { :class => 'form-horizontal' } do |f| %>

<div class="control-group">
    <%= f.label :issue, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :issue, :class => 'text_field', :cols => "30", :rows => "8" %>
    </div>
  </div>
 
  <div class="control-group">
    <%= f.label :trouble_shooting_steps, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :trouble_shooting_steps, :class => 'text_field', :cols => "30", :rows => "8" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :status, ['Issue Solved','Issue Not Solved','Under Screening'] %>
    </div>
  </div>
   <div class="form-actions">
<form class="form-search">
    <button type="submit" class="btn">Proceed</button>
    </form>   
  </div>
  <% end %>
</html>

app/views/sixmonth_customers/index.html.erb
<%- model_class = SixmonthCustomer -%>
<div align="center">
<a href="http://rkkinfosystem.herokuapp.com/instant_customers"><button>One Time customers</button></a>
<a href="http://rkkinfosystem.herokuapp.com/oneyear_customers"><button>One Year customers</button></a>
<a href="http://rkkinfosystem.herokuapp.com/twoyear_customers"><button>Two year customers</button></a>

</div>
<div align="right">
<%= form_tag :controller => 'login2', 
             :action => 'logout' do %>
<%= submit_tag 'Logout', :class => 'ctrl' %>
<% end %>
</div>
<h4><center>These customers have applied for Six months service.</center></h4>
<h5><center>These Customers have given $129/£129</center></h5>
<br/><br/>
<form class="form-search">

    <%= text_field_tag :emp_no, params[:emp_no] %>

    <button type="submit" class="btn">Search</button>
    </form>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:emp_no) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:e_mail) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
                  <th><%= model_class.human_attribute_name(:plan) %></th>

      <th><%= model_class.human_attribute_name(:issue) %></th>
      <th><%= model_class.human_attribute_name(:trouble_shooting_steps) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>

      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sixmonth_customers.each do |sixmonth_customer| %>
      <tr>
        <td><%= link_to sixmonth_customer.id, sixmonth_customer_path(sixmonth_customer) %></td>
        <td><%= sixmonth_customer.emp_no %></td>
        <td><%= sixmonth_customer.name %></td>
        <td><%= sixmonth_customer.e_mail %></td>
        <td><%= sixmonth_customer.phone %></td>
                        <td><%=  sixmonth_customer.plan %></td>

        <td><%= sixmonth_customer.issue %></td>
        <td><%= sixmonth_customer.trouble_shooting_steps %></td>
        <td><%= sixmonth_customer.status %></td>
        <td><%=l sixmonth_customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sixmonth_customer_path(sixmonth_customer), :class => 'btn btn-mini' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sixmonth_customers/new.html.erb
<html>
<div class="item hover" style="color:#16C970">

<Center><h5>You have opted for Six month service.</h5></center>
</div>
<br>
<%= render :partial => 'form' %>
</html>

app/views/sixmonth_customers/show.html.erb
<html>
<%- model_class = SixmonthCustomer -%>

<dl class="dl-horizontal">
  <dt style="color:#16C970"><strong><%= model_class.human_attribute_name(:emp_no) %>:</strong></dt>
  <dd style="color:#1C9DD6"><%= @sixmonth_customer.emp_no %></dd>
  <dt style="color:#16C970"><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd style="color:#1C9DD6"><%= @sixmonth_customer.name %></dd>
  <dt style="color:#16C970"><strong><%= model_class.human_attribute_name(:e_mail) %>:</strong></dt>
  <dd style="color:#1C9DD6"><%= @sixmonth_customer.e_mail %></dd>
  <dt style="color:#16C970"><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd style="color:#1C9DD6"><%= @sixmonth_customer.phone %></dd>
   <dt style="color:#16C970"><strong><%= model_class.human_attribute_name(:plan) %>:</strong></dt>
  <dd style="color:#1C9DD6"><%= @sixmonth_customer.plan %></dd>

</dl>


</html>